on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      id : test
      uses: returntocorp/semgrep-rules-test-action@master
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: tests
        path: ${{ steps.test.outputs.output_dir }}
