on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-rules-test-action@master
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 1214
